# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Darwin_x86_64.tar.gz"
      sha256 "b9188c512510bf5603b4f0f41a52c19c3ebd6f2f0204612b3b517f1d65827adc"

      def install
        bin.install "bin/hammer"
      end
    end
    if Hardware::CPU.arm?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Darwin_arm64.tar.gz"
      sha256 "2f5f500faa637d5202b095b1feb7ac0a53a47aef461240490458e25c1cf05543"

      def install
        bin.install "bin/hammer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Linux_x86_64.tar.gz"
      sha256 "9fa1cd0557de08afada9823b9e776e047cae809d1fec349f7fa4d4fd5560eb62"
      def install
        bin.install "bin/hammer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Linux_arm64.tar.gz"
      sha256 "9fe19b0137677f0646939a3e72e3d8bfeb9840d5af9a408e9c69bc04aae30ced"
      def install
        bin.install "bin/hammer"
      end
    end
  end

  test do
    system "#{bin}/hammer version"
  end
end
