# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc ""
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://o.xdb.be/hammer/release/v0.0.4/hammer_Darwin_x86_64.tar.gz"
      sha256 "370420d7a2604ea3d14f11d1107351629ee50674b836ef94ca7cbd3744fad0a8"

      def install
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm?
      url "https://o.xdb.be/hammer/release/v0.0.4/hammer_Darwin_arm64.tar.gz"
      sha256 "693910e4f8482c6f2ee446587244ac85e8d10483edb4ad3f27fdb6f9059e01f3"

      def install
        bin.install "hammer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.4/hammer_Linux_x86_64.tar.gz"
      sha256 "7e6aab30086e4a8b9b736201b8e20fa68ce740fa4e61b5197a924ea862a53167"
      def install
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.4/hammer_Linux_arm64.tar.gz"
      sha256 "c5a147a38e2abf378a8029c63921237e2c095606f6462fe21cd37e3f3dc9b1af"
      def install
        bin.install "hammer"
      end
    end
  end

  test do
    system "#{bin}/hammer version"
  end
end
