# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hammer < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Darwin_x86_64.tar.gz"
      sha256 "c1465f43a55d405ddd28afd458ff5e7855f7479cc42ba37dbebf10e9f1154eb0"

      def install
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Darwin_arm64.tar.gz"
      sha256 "08286f439bf4f08208795075fe9c234ba6bdf116fec050724ce8739306165bd4"

      def install
        bin.install "hammer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Linux_x86_64.tar.gz"
      sha256 "44d8eed81ec57d5281c4d7cc9205198328bebcb6c8275c0c9105e5b294fcf4dc"
      def install
        bin.install "hammer"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://o.xdb.be/hammer/release/v0.0.3/hammer_Linux_arm64.tar.gz"
      sha256 "ac04e5ac33e28a54760e77e83b1fc8e7a797593eb76d4af4d6f9b76301ad9f79"
      def install
        bin.install "hammer"
      end
    end
  end

  test do
    system "#{bin}/hammer version"
  end
end
